# -*- coding: utf-8 -*-
"""myshcodx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeKw4YvaufNWcxdscfbodY80KSrb1mxl
"""

print("🔥 myshscodx v2.0 🔥")
print("The Language of Dragons")
print("-" * 30)


class Myshscodx:

    def __init__(self):
        self.vars = {}

    def eval_expr(self, expr):
        return eval(expr, {}, self.vars)

    def run(self, code):

        lines = []

        for line in code.splitlines():
            line = line.strip()

            if not line:
                continue

            if line.startswith("#"):
                continue

            lines.append(line)

        self.execute_block(lines)

    def execute_block(self, lines):

        i = 0

        while i < len(lines):

            line = lines[i]

            # Dracarys (variable declaration)
            if line.startswith("Dracarys "):

                rest = line[len("Dracarys "):]

                var_name, expr = rest.split("=", 1)

                var_name = var_name.strip()
                expr = expr.strip()

                self.vars[var_name] = self.eval_expr(expr)

            # Rytsas (print)
            elif line.startswith("Rytsas "):

                expr = line[len("Rytsas "):].strip()

                if expr.startswith('"') and expr.endswith('"'):
                    print(expr[1:-1])

                else:
                    print(self.eval_expr(expr))

            # Zaldrizes (if)
            elif line.startswith("Zaldrizes "):

                condition = line[len("Zaldrizes "):].strip()

                block = []
                else_block = []

                depth = 1
                j = i + 1
                in_else = False

                while j < len(lines):

                    current = lines[j]

                    if current.startswith("Zaldrizes "):
                        depth += 1

                    elif current == "Darilaros":
                        depth -= 1

                        if depth == 0:
                            break

                    elif current == "MunaZaldrizoti" and depth == 1:
                        in_else = True
                        j += 1
                        continue

                    if in_else:
                        else_block.append(current)
                    else:
                        block.append(current)

                    j += 1

                if self.eval_expr(condition):
                    self.execute_block(block)

                else:
                    self.execute_block(else_block)

                i = j

            # Valonqar (for loop)
            elif line.startswith("Valonqar "):

                loop_part = line[len("Valonqar "):]

                left, end_value = loop_part.split("TO")

                var_name, start_value = left.split("=")

                var_name = var_name.strip()
                start_value = int(self.eval_expr(start_value.strip()))
                end_value = int(self.eval_expr(end_value.strip()))

                block = []

                depth = 1
                j = i + 1

                while j < len(lines):

                    current = lines[j]

                    if current.startswith("Valonqar "):
                        depth += 1

                    elif current == "Darilaros":
                        depth -= 1

                        if depth == 0:
                            break

                    block.append(current)
                    j += 1

                for value in range(start_value, end_value + 1):

                    self.vars[var_name] = value
                    self.execute_block(block)

                i = j

            # Unknown command
            else:

                print(f"Dragon Error: Unknown command -> {line}")

            i += 1


# ===========================
# SAMPLE PROGRAM
# ===========================

program = """
Dracarys n = 7

Valonqar i = 1 TO 10
Rytsas n * i
Darilaros
"""

engine = Myshscodx()
engine.run(program)